src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan("today",message="la date d'arrivée doit etre ultérieure à la date d'aujourd'hui" ,groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")    
     *  @Assert\GreaterThan(propertyPath="startDate",message="la date d'arrivée doit etre ultérieure à la date d'aujourd'hui !") 
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="float")
     */
    private $montant;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Undocumented function 
     *@ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function prePersist(){
        if(empty($this->createdAt)){
            $this->CreatedAt = new \DateTime();
        }
        if(empty($this->montant)){
            // prix de l'annonce * nombre de jour
           $this->montant= $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function getDuration(){
        $diff =$this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function isBookableDates(){
        // il faut connaitre les dates qui sont impossibles pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays();
        // il faut comparer les dates choisies avec les dates impossible
        $bookingDays  =$this->getDays();

            $formatDay=function($day){
                return $day->format('Y-m-d');
            };
        //tableau des chaines de caractéres de mes journées
        $days         =  array_map($formatDay, $bookingDays);

        $notAvailable = array_map($formatDay,$notAvailableDays);

        foreach($days as $day){
            if(array_search($day,$notAvailable) !== false) return false;
        }

        return true;
    }
    /**
     * permet de récupérer un tableau des journées qui correspondent à ma réservation
     *
     * @return array
     */
        public function getDays(){
            $resultat=range(
                $this->startDate->getTimestamp(),
                $this->endDate->getTimestamp(),
                24 * 60 *60
            );

            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d',$dayTimestamp));
            },$resultat);

            return $days;
        }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;
    /**
     * @Assert\EqualTo(propertyPath="hash",message="Vous n'avez pas correctement confirmé votre mot de passe")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    /**
    * @ORM\Column(type="json")
    */
    private $roles = [];

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tel;

    public function getFullName(){
        return "{$this->firstname} {$this->lastName}";
    }

    /**
     * Permet d'initiliser le slug
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug= $slugify->slugify($this->firstname.''.$this->lastName);
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

         public function getRoles(): array
         {
            $roles = $this->roles;
           
            $roles[] = 'ROLE_USER';
          
            return array_unique($roles);
          }

          public function setRoles(array $roles): self
                {
                $this->roles = $roles;
                return $this;
                }


          public function getPassword()
          {
             return $this->hash;
          }

          public function getSalt()
          {
              // TODO: Implement getSalt() method.
          }

          public function getUsername()
          {
              return $this->email;
          }

          public function eraseCredentials()
          {
              // TODO: Implement eraseCredentials() method.
          }

          /**
           * @return Collection|Booking[]
           */
          public function getBookings(): Collection
          {
              return $this->bookings;
          }

          public function addBooking(Booking $booking): self
          {
              if (!$this->bookings->contains($booking)) {
                  $this->bookings[] = $booking;
                  $booking->setBooker($this);
              }

              return $this;
          }

          public function removeBooking(Booking $booking): self
          {
              if ($this->bookings->removeElement($booking)) {
                  // set the owning side to null (unless already changed)
                  if ($booking->getBooker() === $this) {
                      $booking->setBooker(null);
                  }
              }

              return $this;
          }

          /**
           * @return Collection|Comment[]
           */
          public function getComments(): Collection
          {
              return $this->comments;
          }

          public function addComment(Comment $comment): self
          {
              if (!$this->comments->contains($comment)) {
                  $this->comments[] = $comment;
                  $comment->setUser($this);
              }

              return $this;
          }

          public function removeComment(Comment $comment): self
          {
              if ($this->comments->removeElement($comment)) {
                  // set the owning side to null (unless already changed)
                  if ($comment->getUser() === $this) {
                      $comment->setUser(null);
                  }
              }

              return $this;
          }

          public function getTel(): ?int
          {
              return $this->tel;
          }

          public function setTel(?int $tel): self
          {
              $this->tel = $tel;

              return $this;
          }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends AbstractType
{
    private $transformer;
    public function __construct(FrenchToDateTimeTransformer $transformer){
        $this->transformer = $transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate',TextType::class, [
                'label'=>"date d'arrivée",
                'attr' => [
                    'placeholder' => "la date à laquelle vous comptez arriver"]
                
               
                
            ])
            ->add('endDate',TextType::class, [
                'label'=>"date de départ",
                'attr' => [
                    'placeholder' => "la date à laquelle vous quittrz les lieux"]
                
                
            ])
            ->add('comment',TextareaType::class, [
                'label'=>false,
                'required'=>false
              

            ])
         
        ;
        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups'=>['Default','front']
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    #[Route('/ads/{slug}/book', name: 'booking_create')]
    public function create(Ad $ad,Request $request,EntityManagerInterface $manager): Response
    {
        $booking =new Booking();
        $form= $this->createForm(BookingType::class,$booking);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid() ){

            $user =$this->getUser();
            $booking->setBooker($user)->setAd($ad);

            // si les dates ne sont pas disponibles ,message d'erreur
            if(!$booking->isBookableDates()){
                $this->addFlash(
                    'warning',"les dates que vous avez choisi ne peuvent etre réservées : elles sont déja prises."
                );
            }else{
                $manager->persist($booking);
                $manager->flush(); 
                return $this->redirectToRoute('booking_show',['id'=>$booking->getId(),
             'withAlert'=>true]);
            }
       

        }
        return $this->render('booking/index.html.twig', [
            'ad'=>$ad,
            'form'=>$form->createView(),
        ]);
    }

    /**
     * @Route("/booking/{id}",name="booking_show")
     */

     public function show (Booking $booking,Request $request,EntityManagerInterface $manager): Response{

        $comment=new Comment();
        $form=$this->createForm(CommentType::class,$comment);
        $form->handleRequest($request);
             if ($form->isSubmitted() && $form->isValid()  ) {
               
                 $comment->setAd($booking->getAd());
                 $comment->setUser($this->getUser());
                 $comment->setCreatedAt(new \DateTimeImmutable('now'));
             $entityManager = $this->getDoctrine()->getManager();
             $entityManager->persist($comment);
             $entityManager->flush();
             $this->addFlash(
                'success',
                "Votre commentaire a bien été pris en compte !");
                return $this->redirectToRoute('booking_show', ['id' => $booking->getId()]);
                
             }
        return $this->render('booking/show.html.twig',[
           'booking'=>$booking,
           'form'=>$form->createView()
        ]);
     }
}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reserver l'annonce {{ad.titre}}!{% endblock %}
{% block stylesheets %}

{% endblock stylesheets %}
{% block body %}
<section style="padding-top: 50px;">
<div class="container">

            <h1>Réservez pour l'annonce : {{ad.titre}}</h1>
            <p>Vous étes sur le point de réserver le bien de <strong>{{ad.author.username}}</strong>,dites nous tout,on s'occupe du reste !</p>


            {{form_start(form)}}

            <div class="alert alert light">
                <h2>Commencez par nous dire quelles sont les dates qui vous intéressent !</h2>
                <div class="row">
                    <div class="col">
                    {{form_row(form.startDate)}}
                    </div>
                    <div class="col">
                      {{form_row(form.endDate)}}
                    </div>
                </div>
            

            <h4>Montant du séjour : <span id="montant">...</span> DT</h4>
            <span id="days">0</span> nuit(s) à {{ad.price}} / nuit
            <h4 class="mt-3">Vous avez un commentaire ?</h4>
            {{form_row(form.comment)}}
            </div>
            
            <h2>Vous avez terminé !</h2>
             <p>Vacances de réve ? Hébergement pour le boulot ? peu importe , on est avec vous !</p>
             <Button type="submit" class="btn btn-success">Je réserve !</Button>
            {{form_end(form)}}
</div>


<style>
.datepicker table tr td.disabled, .datepicker table tr td.disabled:hover {

    color : firebrick !important;
}
</style>

<script>
  $(document).ready(function(){
    $('#booking_startDate, #booking_endDate').datepicker({
      format: 'dd/mm/yyyy',
      datesDisabled:[
        {% for day in ad.notAvailableDays %}
            "{{ day.format('d/m/Y') }}",
        {% endfor %}
      ],
      startDate : new Date(),

    });

     $('#booking_startDate, #booking_endDate').on('change', calculateMontant);
  });

  function calculateMontant (){
    const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

    const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

      if(startDate && endDate && startDate < endDate){
        const DAY_TIME = 24 * 60 *60 *1000;
        const interval = endDate.getTime() - startDate.getTime();
        const days = interval / DAY_TIME;
        const montant =days * {{ad.price}};
        $('#days').text(days);
        $('#montant').text(montant.toLocaleString('fr-FR'));
      }
  }
</script></section>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n° {{booking.id}}!{% endblock %}

{% block body %}
<section style="padding-top: 50px;">
<div class="container">
    <h1>Votre Réservation (n°{{booking.id}})</h1>

         {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">
                    Bravo !
                </h4>

                <p>
                Votre réservation auprés de <strong> <a href="{{path("user_show",{'slug':booking.ad.author.slug})}}" >{{booking.ad.author.firstname}}{{booking.ad.author.lastname}}</strong>
               pour l'annonce <strong><a href="{{ path("ads_show",{'slug':booking.ad.slug}) }}" >{{booking.ad.titre}}</strong>
               a bien été prise en compte !
                </p>
            </div>
         {% endif %}

    <div class="row">
        <div class="col">
        <div class="alert alert-light">
            <h2>Détails</h2>
            <d1 class="row">
                <dt class="col-md-4">Numero</dt>
                <dd class="col-md-8">{{booking.id}}</dd>
                <dt class="col-md-4">Date d'arrivée</dt>
                <dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
                <dt class="col-md-4">Date de départ</dt>
                <dd class="col-md-8">{{booking.endDate | date('d/m/Y')}}</dd>
                <dt class="col-md-4">Nombre de nuits</dt>
                <dd class="col-md-8">{{booking.duration}}</dd>
                <dt class="col-md-4">Montant total</dt>
                <dd class="col-md-8">{{booking.montant}} DT</dd>
                <dt class="col-md-4">Commentaire</dt>
                <dd class="col-md-8">{{booking.comment | default('Aucun commentaire')}}</dd>
            </d1>

            <hr>
            <h2 class="alert-heading">Votre hote</h2>
            <div class="row mb-3">
                <div class="col-3">
                  <img src="{{booking.ad.author.picture}}"  class="avatar avatar-medium" alt="avatar de {{booking.ad.author.firstname}} {{booking.ad.author.lastname}}" >
                </div>
                <div class="col-9">
                <h4>
                    <a href="{{path('user_show',{'slug': booking.ad.author.slug})}}"> {{booking.ad.author.firstname}} {{booking.ad.author.lastname}}</a>
                </h4>

                <span class="badge badge-primary">
                {{booking.ad.author.ads | length}} annonces

                </span>
                </div>
            </div>
            {{booking.ad.author.description | raw}}<br>
            <br>
            <a href="{{path('user_show',{'slug': booking.ad.author.slug})}}" class="btn btn-primary">Plus d'info sur {{booking.ad.author.lastname}}</a>
        </div>  

        <div class="alert alert-light" id="comment">
            <h2 class="alert-heading">Votre avis compte !</h2>

            {% if date() > date(booking.endDate) %}
            {% set comment = booking.ad.getCommentFromUser(app.user) %}
            {% if comment is not null %}
            <blockquote>
                {{comment.content}}
            </blockquote>
                <strong>Note : </strong> 
                  <span class="rating">
                                  {% for i in 1..5 %}
                                  {% if i <= comment.rating %} 
                                  <i class="fas fa-star"></i>
                                  {% else %}
                                  <i class="far fa-star"></i>
                                  {% endif %}
                                  {% endfor %}
                                </span>
            {% else %}
                        {{ form_start(form) }}
                         {{ form_widget(form) }}
                         
                         <button type="submit" class="btn btn-success btn-rounded" >confirmer !</button>
                          {{ form_end(form) }}
            {% endif %}
               
            {% else %}
                <p>Vous ne pourrez pas noter cette annonce tant que votre voyage ne sera pas complet !</p>
            {% endif %}
        </div>

        </div>
        <div class="col">
            <div class="alert alert-light">
                <h2 class="alert-heading">
                    Votre Hébergement
                </h2>
                <h4>
                    <a href="{{path('ads_show',{'slug': booking.ad.slug})}}">{{booking.ad.titre}}</a>
                </h4>
                    <img src="{{booking.ad.coverImage}}" alt="Image de {{booking.ad.titre}}" class="img-fluid">

                    {{booking.ad.contente | raw }}
                        <br><br>
                    <a href="{{path('ads_show',{'slug': booking.ad.slug})}}" class="btn btn-primary">Plus d'informations</a>
            </div>
        </div>
    
    </div>




</div></section>
{% endblock %}